### ISSUE TITLE
exception related to storing tomcat sessions in datastore

### ISSUE THREAD

**Issue by papudesi** [GoogleCloudPlatform/tomcat-runtime#124]
```
com.google.cloud.datastore.DatastoreException: cannot write more than 500 entities in a single call
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.translate(HttpDatastoreRpc.java:128)
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.commit(HttpDatastoreRpc.java:154)
	at com.google.cloud.datastore.DatastoreImpl$5.call(DatastoreImpl.java:418)
	at com.google.cloud.datastore.DatastoreImpl$5.call(DatastoreImpl.java:415)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:94)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:54)
	at com.google.cloud.datastore.DatastoreImpl.commit(DatastoreImpl.java:414)
	at com.google.cloud.datastore.DatastoreImpl.commitMutation(DatastoreImpl.java:408)
	at com.google.cloud.datastore.DatastoreImpl.delete(DatastoreImpl.java:393)
	at com.google.cloud.runtimes.tomcat.session.DatastoreStore.processExpires(DatastoreStore.java:295)
	at com.google.cloud.runtimes.tomcat.session.DatastoreManager.processExpires(DatastoreManager.java:209)
	at org.apache.catalina.session.ManagerBase.backgroundProcess(ManagerBase.java:537)
	at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5572)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1388)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1392)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1392)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1360)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.datastore.v1.client.DatastoreException: cannot write more than 500 entities in a single call, code=INVALID_ARGUMENT
	at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:126)
	at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:169)
	at com.google.datastore.v1.client.RemoteRpc.call(RemoteRpc.java:89)
	at com.google.datastore.v1.client.Datastore.commit(Datastore.java:84)
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.commit(HttpDatastoreRpc.java:152)
	... 16 more
```

Trying to get an understanding of cause and severity...

**Comment by meltsufin** [comment]
Thanks for the issue submission.
It looks like a bug with the batch commit.
You probably have more than 500 keys in your session, and the session module saves them in a single batch operation.
See: https://cloud.google.com/datastore/docs/concepts/limits
"500 - Maximum number of entities that can be passed to a Commit operation in the Cloud Datastore API"

**Comment by papudesi** [comment]
@meltsufin we have only a handful of keys per session, but we have a lot of concurrent sessions.

**Comment by papudesi** [comment]
@meltsufin re: severity, assuming individual sessions have few keys, it appears the issue is limited to handling session expiry and clearing all sessions. which means that once the issue begins, sessions just never expire?

**Comment by meltsufin** [comment]
Ah! That makes sense. Seems like the expiry logic needs to be fixed to deal with a large number of sessions.
